def encontrar_duplicados(lista_nomes):
    """
    Encontra e retorna nomes duplicados em uma lista de tuplas
    """
    contagem = {}
    for nome, significado, origem, motivacao in lista_nomes:
        if nome in contagem:
            contagem[nome].append((significado, origem, motivacao))
        else:
            contagem[nome] = [(significado, origem, motivacao)]
    
    # Filtrar apenas os que têm mais de uma entrada
    return {nome: detalhes for nome, detalhes in contagem.items() if len(detalhes) > 1}

# Exemplo de uso

nomes = [
    ("Alice", "Nobre", "Hebraica", "Escolhido pelos pais por tradição"),
    ("Bruno", "Castanho, moreno", "Germânica", "Gostaram do som do nome"),
    ("Clara", "Brilhante, clara", "Latina", "Significado positivo"),
    ("Daniel", "Deus é meu juiz", "Hebraica", "Homenagem a um parente"),
    ("Eduardo", "Guardião rico", "Anglo-saxã", "Escolhido pelo significado"),
    ("Fernanda", "Corajosa, ousada", "Germânica", "Nome clássico na família"),
    ("Gabriel", "Homem de Deus", "Hebraica", "Escolha religiosa"),
    ("Helena", "Tocha, luz brilhante", "Grega", "Nome tradicional"),
    ("Isabela", "Promessa de Deus", "Hebraica", "Nome escolhido pelos pais"),
    ("João", "Deus é gracioso", "Hebraica", "Nome muito comum e querido"),
    ("Karina", "Pura", "Escandinava", "Escolha dos avós"),
    ("Lucas", "Iluminado", "Latina", "Nome bíblico"),
    ("Mariana", "Aquela que é amada", "Latina", "Nome popular"),
    ("Nicolas", "Vencedor do povo", "Grega", "Nome em homenagem a um amigo"),
    ("Olga", "Sagrada", "Escandinava", "Nome escolhido pela avó"),
    ("Pedro", "Pedra", "Grega", "Nome forte"),
    ("Quintino", "Quinto", "Latina", "Nome tradicional"),
    ("Rafaela", "Deus curou", "Hebraica", "Escolha familiar"),
    ("Sofia", "Sabedoria", "Grega", "Nome de origem clássica"),
    ("Tiago", "Suplantador", "Hebraica", "Nome tradicional"),
    ("Vitória", "Vitória", "Latina", "Escolha dos pais"),
    ("Arthur", "Nobre corajoso", "Celta", "Nome de rei lendário"),
    ("Beatriz", "Aquela que traz alegria", "Latina", "Nome de personagem literária"),
    ("Caio", "Alegre", "Latina", "Nome histórico romano"),
    ("Débora", "Abelha", "Hebraica", "Nome bíblico"),
    ("Enzo", "Proprietário de terras", "Italiana", "Nome da moda"),
    ("Flávia", "Loura", "Latina", "Escolhido pela cor do cabelo"),
    ("Gustavo", "Cajado dos deuses", "Germânica", "Nome de ancestral"),
    ("Heloísa", "Guerreira famosa", "Germânica", "Nome histórico"),
    ("Igor", "Guerreiro", "Russa", "Nome forte"),
    ("Júlia", "Jovem", "Latina", "Nome clássico"),
    ("Kevin", "Amado", "Irlandesa", "Nome de artista"),
    ("Larissa", "Alegre", "Grega", "Nome mitológico"),
    ("Mateus", "Dom de Deus", "Hebraica", "Nome bíblico"),
    ("Natália", "Natal", "Latina", "Nascida no natal"),
    ("Otávio", "Oitavo", "Latina", "Oitavo filho"),
    ("Paula", "Pequena", "Latina", "Nome simples"),
    ("Raquel", "Ovelha de Deus", "Hebraica", "Nome bíblico"),
    ("Samuel", "Nome de Deus", "Hebraica", "Escolha religiosa"),
    ("Tatiane", "Rainha", "Russa", "Nome exótico"),
    ("Vinícius", "Vitorioso", "Latina", "Nome de poeta"),
    ("Amanda", "Amável", "Latina", "Significado positivo"),
    ("Breno", "Rei", "Celta", "Nome forte"),
    ("Camila", "Ajudante", "Latina", "Nome tradicional"),
    ("Diego", "Supremo", "Espanhola", "Nome popular"),
    ("Elisa", "Consagrada a Deus", "Hebraica", "Escolha religiosa"),
    ("Felipe", "Amante de cavalos", "Grega", "Nome histórico"),
    ("Giovanna", "Deus é gracioso", "Italiana", "Versão italiana de Joana"),
    ("Henrique", "Governante do lar", "Germânica", "Nome de reis"),
    ("Ivana", "Deus é gracioso", "Eslava", "Variante de Joana"),
    ("Jorge", "Agricultor", "Grega", "Nome de santo"),
    ("Letícia", "Alegria", "Latina", "Significado positivo"),
    ("Murilo", "Pequeno muro", "Latina", "Nome incomum"),
    ("Nádia", "Esperança", "Russa", "Nome simples"),
    ("Osvaldo", "Poder divino", "Germânica", "Nome antigo"),
    ("Priscila", "Antiga", "Latina", "Nome bíblico"),
    ("Quésia", "Árvore aromática", "Tupi", "Nome indígena"),
    ("Renato", "Renascido", "Latina", "Significado de renovação"),
    ("Simone", "Deus ouve", "Hebraica", "Nome bíblico"),
    ("Thiago", "Suplantador", "Hebraica", "Variante de Tiago"),
    ("Uriel", "Deus é minha luz", "Hebraica", "Nome angelical"),
    ("Valéria", "Saúde", "Latina", "Significado positivo"),
    ("Wagner", "Carroceiro", "Germânica", "Nome de compositor"),
    ("Xênia", "Hospitalidade", "Grega", "Nome diferente"),
    ("Yasmin", "Flor de jasmim", "Persa", "Nome floral"),
    ("Zacarias", "Deus lembrou", "Hebraica", "Nome bíblico"),
    ("Adriana", "Do mar", "Latina", "Nome geográfico"),
    ("Bernardo", "Fortaleza do urso", "Germânica", "Nome forte"),
    ("Cristina", "Cristã", "Grega", "Escolha religiosa"),
    ("Davi", "Amado", "Hebraica", "Nome bíblico"),
    ("Estela", "Estrela", "Latina", "Significado celestial"),
    ("Fabrício", "Artífice", "Latina", "Nome histórico"),
    ("Geovana", "Deus é gracioso", "Italiana", "Variante de Giovanna"),
    ("Hugo", "Inteligente", "Germânica", "Nome curto"),
    ("Isis", "Deusa egípcia", "Egípcia", "Nome mitológico"),
    ("Jefferson", "Filho de Jeffrey", "Inglesa", "Nome americano"),
    ("Kátia", "Pura", "Russa", "Variante de Catarina"),
    ("Leandro", "Homem-leão", "Grega", "Nome mitológico"),
    ("Mirella", "Admirável", "Latina", "Nome poético"),
    ("Norberto", "Brilhante do norte", "Germânica", "Nome antigo"),
    ("Orlando", "Terra famosa", "Germânica", "Nome literário"),
    ("Patrícia", "Nobre", "Latina", "Nome clássico"),
    ("Queila", "Coroa", "Hebraica", "Nome diferente"),
    ("Rogério", "Lança famosa", "Germânica", "Nome forte"),
    ("Sueli", "Graciosa", "Tupi", "Nome indígena"),
    ("Tomás", "Gêmeo", "Aramaica", "Nome bíblico"),
    ("Ubirajara", "Senhor da lança", "Tupi", "Nome indígena"),
    ("Vera", "Verdade", "Russa", "Nome simples"),
    ("Wellington", "Cidade prospera", "Inglesa", "Nome geográfico"),
    ("Xisto", "Polido", "Grega", "Nome incomum"),
    ("Yara", "Senhora das águas", "Tupi", "Nome indígena"),
    ("Zara", "Princesa", "Árabe", "Nome real"),
    ("Aline", "Bela", "Grega", "Nome simples"),
    ("Bento", "Abençoado", "Latina", "Nome religioso"),
    ("Cauê", "Aquele que vê", "Tupi", "Nome indígena"),
    ("Diana", "Divina", "Latina", "Nome mitológico"),
    ("Eliane", "Deus respondeu", "Hebraica", "Significado religioso"),
    ("Fabiano", "Agricultor", "Latina", "Nome histórico"),
    ("Gisele", "Flecha", "Germânica", "Nome de modelo"),
    ("Heitor", "Aquele que segura", "Grega", "Nome heróico"),
    ("Iracema", "Lábios de mel", "Tupi", "Nome literário"),
    ("Jonas", "Pomba", "Hebraica", "Nome bíblico"),
    ("Kleber", "Famoso", "Germânica", "Nome forte"),
    ("Lorena", "Natural da Lorena", "Francesa", "Nome geográfico"),
    ("Marcos", "Guerreiro", "Latina", "Nome bíblico"),
    ("Noemi", "Agradável", "Hebraica", "Nome bíblico"),
    ("Odete", "Rica", "Germânica", "Nome antigo"),
    ("Paolo", "Pequeno", "Italiana", "Variante de Paulo"),
    ("Quirino", "Lança", "Latina", "Nome histórico"),
    ("Rute", "Amizade", "Hebraica", "Nome bíblico"),
    ("Sérgio", "Servo", "Latina", "Nome comum"),
    ("Tânia", "Fada rainha", "Russa", "Nome literário"),
    ("Urbano", "Da cidade", "Latina", "Nome histórico"),
    ("Vanda", "Andarilha", "Eslava", "Nome diferente"),
    ("Walter", "Governante do exército", "Germânica", "Nome forte"),
    ("Xavier", "Novo lar", "Basco", "Nome de santo"),
    ("Yvette", "Arco de teixo", "Francesa", "Nome diferente"),
    ("Zípora", "Pássaro", "Hebraica", "Nome bíblico"),
    ("Aurora", "Amanhecer", "Latina", "Significado poético"),
    ("Bryan", "Nobre", "Celta", "Nome moderno"),
    ("Célia", "Céu", "Latina", "Significado celestial"),
    ("Dênis", "Deus do vinho", "Grega", "Nome mitológico"),
    ("Elisa", "Deus é juramento", "Hebraica", "Nome bíblico"),
    ("Fábio", "Agricultor", "Latina", "Nome histórico"),
    ("Gilda", "Oferta a Deus", "Germânica", "Nome antigo"),
    ("Hélio", "Sol", "Grega", "Nome mitológico"),
    ("Íris", "Arco-íris", "Grega", "Nome mitológico"),
    ("Joaquim", "Deus estabelecerá", "Hebraica", "Nome bíblico"),
    ("Kiara", "Clara", "Italiana", "Variante de Clara"),
    ("Luciana", "Luz", "Latina", "Significado positivo"),
    ("Márcio", "Guerreiro", "Latina", "Nome forte"),
    ("Nair", "Negra", "Árabe", "Nome simples"),
    ("Oscar", "Lança de Deus", "Germânica", "Nome de premiação"),
    ("Penélope", "Tecelã", "Grega", "Nome mitológico"),
    ("Quésia", "Canela", "Tupi", "Nome aromático"),
    ("Ronaldo", "Conselheiro do governante", "Germânica", "Nome de jogador"),
    ("Selma", "Proteção divina", "Germânica", "Nome poético"),
    ("Túlio", "O que vem do povo", "Latina", "Nome histórico"),
    ("Úrsula", "Pequena ursa", "Latina", "Nome histórico"),
    ("Vicente", "Vencedor", "Latina", "Nome forte"),
    ("Wanda", "Andarilha", "Eslava", "Nome diferente"),
    ("Xande", "Defensor da humanidade", "Grega", "Abreviação de Alexandre"),
    ("Yolanda", "Flor violeta", "Grega", "Nome floral"),
    ("Zeno", "Presente de Zeus", "Grega", "Nome filosófico"),
    ("Amarilis", "Brilhante", "Grega", "Nome floral"),
    ("Berenice", "Portadora da vitória", "Grega", "Nome histórico"),
    ("Cícero", "Grão-de-bico", "Latina", "Nome histórico"),
    ("Dália", "Flor", "Grega", "Nome floral"),
    ("Edson", "Filho de Eduardo", "Inglesa", "Nome moderno"),
    ("Fabíola", "Pequena agricultora", "Latina", "Nome histórico"),
    ("Geraldo", "Lança governante", "Germânica", "Nome forte"),
    ("Hilda", "Guerreira", "Germânica", "Nome antigo"),
    ("Inácio", "Fogo", "Latina", "Nome religioso"),
    ("Jade", "Pedra preciosa", "Espanhola", "Nome de gema"),
    ("Kauã", "Gavião", "Tupi", "Nome indígena"),
    ("Lívia", "Azulada", "Latina", "Nome histórico"),
    ("Moisés", "Salvo das águas", "Hebraica", "Nome bíblico"),
    ("Nelson", "Filho de Neil", "Inglesa", "Nome moderno"),
    ("Olívia", "Oliveira", "Latina", "Nome de paz"),
    ("Pablo", "Pequeno", "Espanhola", "Variante de Paulo"),
    ("Quitéria", "Calma", "Grega", "Nome histórico"),
    ("Robson", "Filho de Robert", "Inglesa", "Nome moderno"),
    ("Sandra", "Protetora da humanidade", "Grega", "Abreviação de Alexandra"),
    ("Téo", "Presente de Deus", "Grega", "Abreviação de Teodoro"),
    ("Ulysses", "O irritado", "Grega", "Nome mitológico"),
    ("Vânia", "Deus é gracioso", "Russa", "Variante de Ana"),
    ("Wilson", "Filho de Will", "Inglesa", "Nome moderno"),
    ("Ximena", "Ouvinte", "Espanhola", "Nome histórico"),
    ("Yago", "Suplantador", "Espanhola", "Variante de Tiago"),
    ("Zuleica", "Brilhante", "Árabe", "Nome diferente"),
    ("Ariel", "Leão de Deus", "Hebraica", "Nome bíblico"),
    ("Bianca", "Branca", "Italiana", "Nome simples"),
    ("Cauã", "Gavião", "Tupi", "Nome indígena"),
    ("Dara", "Compaixão", "Hebraica", "Nome bíblico"),
    ("Ester", "Estrela", "Hebraica", "Nome bíblico"),
    ("Fiona", "Branca", "Celta", "Nome moderno"),
    ("Glauco", "Brilho cinza", "Grega", "Nome mitológico"),
    ("Hebe", "Juventude", "Grega", "Nome mitológico"),
    ("Ivan", "Deus é gracioso", "Russa", "Variante de João"),
    ("Jussara", "Senhora das águas", "Tupi", "Nome indígena"),
    ("Kaleb", "Cachorro", "Hebraica", "Nome bíblico"),
    ("Luna", "Lua", "Latina", "Nome celestial"),
    ("Mário", "Marte", "Latina", "Nome histórico"),
    ("Nara", "Feliz", "Tupi", "Nome indígena"),
    ("Ovídio", "Ovelha", "Latina", "Nome histórico"),
    ("Perla", "Pérola", "Latina", "Nome de gema"),
    ("Quirino", "Lança", "Latina", "Nome histórico"),
    ("Ravi", "Sol", "Hindu", "Nome diferente"),
    ("Sílvia", "Da floresta", "Latina", "Nome natural"),
    ("Tadeu", "Corajoso", "Aramaica", "Nome bíblico"),
    ("Uriel", "Deus é minha luz", "Hebraica", "Nome angelical"),
    ("Vitor", "Vitorioso", "Latina", "Nome forte"),
    ("Wesley", "Campo do oeste", "Inglesa", "Nome geográfico"),
    ("Xandra", "Protetora da humanidade", "Grega", "Variante de Alexandra"),
    ("Yasmin", "Flor de jasmim", "Persa", "Nome floral"),
    ("Zion", "Paraíso", "Hebraica", "Nome bíblico"),
    ("Abigail", "Fonte de alegria", "Hebraica", "Nome bíblico"),
    ("Bárbara", "Estrangeira", "Grega", "Nome de santa"),
    ("Cíntia", "Mulher do monte Cinto", "Grega", "Nome mitológico"),
    ("Dário", "Aquele que sustenta", "Persa", "Nome histórico"),
    ("Elvira", "Verdadeira", "Germânica", "Nome antigo"),
    ("Fausto", "Afortunado", "Latina", "Nome histórico"),
    ("Gertrudes", "Força da lança", "Germânica", "Nome antigo"),
    ("Horácio", "Tempo", "Latina", "Nome histórico"),
    ("Iara", "Senhora das águas", "Tupi", "Nome indígena"),
    ("Josenildo", "Luta jovem", "Germânica", "Nome composto"),
    ("Kátia", "Pura", "Russa", "Variante de Catarina"),
    ("Léia", "Cansada", "Hebraica", "Nome bíblico"),
    ("Micael", "Quem é como Deus?", "Hebraica", "Variante de Miguel"),
    ("Nelson", "Filho de Neil", "Inglesa", "Nome moderno"),
    ("Odete", "Rica", "Germânica", "Nome antigo"),
    ("Pamela", "Mel", "Grega", "Nome literário"),
    ("Quésia", "Canela", "Tupi", "Nome aromático"),
    ("Raimundo", "Proteção divina", "Germânica", "Nome antigo"),
    ("Sueli", "Graciosa", "Tupi", "Nome indígena"),
    ("Taciano", "Silencioso", "Latina", "Nome histórico"),
    ("Ubaldo", "Coragem", "Germânica", "Nome antigo"),
    ("Valentina", "Saúde", "Latina", "Significado positivo"),
    ("Waldir", "Governante do exército", "Germânica", "Nome forte"),
    ("Xênia", "Hospitalidade", "Grega", "Nome diferente"),
    ("Yuri", "Luz", "Japonesa", "Nome diferente"),
    ("Zilda", "Luta", "Germânica", "Nome antigo"),
    ("Ademar", "Famoso pela nobreza", "Germânica", "Nome antigo"),
    ("Belinda", "Cobra brilhante", "Germânica", "Nome antigo"),
    ("Cremilda", "Protetora famosa", "Germânica", "Nome antigo"),
    ("Dirce", "Dupla", "Grega", "Nome mitológico"),
    ("Edgar", "Lança da prosperidade", "Germânica", "Nome histórico"),
    ("Filomena", "Amiga do canto", "Grega", "Nome histórico"),
    ("Gerson", "Exilado", "Hebraica", "Nome bíblico"),
    ("Hortência", "Jardineira", "Latina", "Nome floral"),
    ("Ivanilde", "Luta jovem", "Germânica", "Nome composto"),
    ("Jacira", "Lua cheia", "Tupi", "Nome indígena"),
    ("Kleber", "Famoso", "Germânica", "Nome forte"),
    ("Ludmila", "Amada do povo", "Eslava", "Nome histórico"),
    ("Marlene", "Combinação de Maria e Madalena", "Germânica", "Nome composto"),
    ("Neide", "Presente", "Grega", "Nome simples"),
    ("Odir", "Rico", "Germânica", "Nome antigo"),
    ("Plínio", "Cheio", "Latina", "Nome histórico"),
    ("Quirina", "Lança", "Latina", "Nome histórico"),
    ("Rosana", "Graciosa como uma rosa", "Latina", "Nome floral"),
    ("Simeão", "Ouvinte", "Hebraica", "Nome bíblico"),
    ("Tereza", "Caçadora", "Grega", "Nome de santa"),
    ("Ubiratã", "Árvore forte", "Tupi", "Nome indígena"),
    ("Vanderlei", "Viajante do vale", "Germânica", "Nome composto"),
    ("Waldete", "Luta do governante", "Germânica", "Nome composto"),
    ("Xisto", "Polido", "Grega", "Nome incomum"),
    ("Yara", "Senhora das águas", "Tupi", "Nome indígena"),
    ("Zacarias", "Deus lembrou", "Hebraica", "Nome bíblico"),
    ("Abner", "Pai da luz", "Hebraica", "Nome bíblico"),
    ("Baltazar", "Deus protege o rei", "Babilônica", "Nome bíblico"),
    ("Cássia", "Canela", "Grega", "Nome aromático"),
    ("Débora", "Abelha", "Hebraica", "Nome bíblico"),
    ("Enoque", "Iniciado", "Hebraica", "Nome bíblico"),
    ("Firmino", "Firme", "Latina", "Nome forte"),
    ("Gideão", "Cortador", "Hebraica", "Nome bíblico"),
    ("Hagar", "Fuga", "Hebraica", "Nome bíblico"),
    ("Ivonete", "Arco de teixo", "Francesa", "Nome diferente"),
    ("Jeremias", "Deus exaltará", "Hebraica", "Nome bíblico"),
    ("Ketlyn", "Pura", "Irlandesa", "Variante de Caitlin"),
    ("Lázaro", "Deus ajudou", "Hebraica", "Nome bíblico"),
    ("Malaquias", "Meu mensageiro", "Hebraica", "Nome bíblico"),
    ("Noé", "Descanso", "Hebraica", "Nome bíblico"),
    ("Oseias", "Salvação", "Hebraica", "Nome bíblico"),
    ("Perséfone", "Aquela que traz destruição", "Grega", "Nome mitológico"),
    ("Queops", "Protegido", "Egípcia", "Nome histórico"),
    ("Raabe", "Amplo", "Hebraica", "Nome bíblico"),
    ("Sansão", "Pequeno sol", "Hebraica", "Nome bíblico"),
    ("Talita", "Menina", "Aramaica", "Nome bíblico"),
    ("Urias", "Deus é minha luz", "Hebraica", "Nome bíblico"),
    ("Vasti", "Bela", "Persa", "Nome bíblico"),
    ("Werther", "Guardião do exército", "Germânica", "Nome literário"),
    ("Xerxes", "Governante", "Persa", "Nome histórico"),
    ("Yasmin", "Flor de jasmim", "Persa", "Nome floral"),
    ("Zebedeu", "Presente de Deus", "Hebraica", "Nome bíblico"),
    ("Aban", "Água", "Persa", "Nome diferente"),
    ("Bastião", "Venerável", "Grega", "Variante de Sebastião"),
    ("Cibele", "Mãe terra", "Frígia", "Nome mitológico"),
    ("Dagmar", "Dia glorioso", "Escandinava", "Nome real"),
    ("Edivaldo", "Governante rico", "Germânica", "Nome composto"),
    ("Fábia", "Agricultora", "Latina", "Nome histórico"),
    ("Giane", "Deus é gracioso", "Italiana", "Variante de Giovana"),
    ("Hilel", "Louvado", "Hebraica", "Nome bíblico"),
    ("Iracema", "Lábios de mel", "Tupi", "Nome literário"),
    ("Jaci", "Lua", "Tupi", "Nome indígena"),
    ("Kailane", "Pura", "Irlandesa", "Variante de Caitlin"),
    ("Líder", "Condutor", "Inglesa", "Nome moderno"),
    ("Maíra", "Filha de Araci", "Tupi", "Nome indígena"),
    ("Nelson", "Filho de Neil", "Inglesa", "Nome moderno"),
    ("Oziel", "Força de Deus", "Hebraica", "Nome bíblico"),
    ("Pérola", "Pérola", "Latina", "Nome de gema"),
    ("Querubim", "Anjo", "Hebraica", "Nome angelical"),
    ("Rute", "Amizade", "Hebraica", "Nome bíblico"),
    ("Salomé", "Paz", "Hebraica", "Nome bíblico"),
    ("Társis", "Pedra preciosa", "Hebraica", "Nome bíblico"),
    ("Uziel", "Força de Deus", "Hebraica", "Nome bíblico"),
    ("Vânia", "Deus é gracioso", "Russa", "Variante de Ana"),
    ("Wanda", "Andarilha", "Eslava", "Nome diferente"),
    ("Xena", "Hospedeira", "Grega", "Nome de personagem"),
    ("Yara", "Senhora das águas", "Tupi", "Nome indígena"),
    ("Zara", "Princesa", "Árabe", "Nome real"),
    ("Açucena", "Flor", "Árabe", "Nome floral"),
    ("Berenice", "Portadora da vitória", "Grega", "Nome histórico"),
    ("Cássio", "Vazio", "Latina", "Nome histórico"),
    ("Dália", "Flor", "Grega", "Nome floral"),
    ("Edna", "Prazer", "Hebraica", "Nome bíblico"),
    ("Floriano", "Florido", "Latina", "Nome floral"),
    ("Glaucia", "Brilho cinza", "Grega", "Nome mitológico"),
    ("Hélia", "Sol", "Grega", "Nome mitológico"),
    ("Ivanir", "Deus é gracioso", "Russa", "Variante de João"),
    ("Jandira", "Abelha", "Tupi", "Nome indígena"),
    ("Kauê", "Aquele que vê", "Tupi", "Nome indígena"),
    ("Lavínia", "Mulher de Lácio", "Latina", "Nome histórico"),
    ("Márcia", "Guerreira", "Latina", "Nome forte"),
    ("Nair", "Negra", "Árabe", "Nome simples"),
    ("Olavo", "Herdeiro", "Escandinava", "Nome real"),
    ("Priscila", "Antiga", "Latina", "Nome bíblico"),
    ("Querência", "Lar", "Espanhola", "Nome poético"),
    ("Rogério", "Lança famosa", "Germânica", "Nome forte"),
    ("Sílvio", "Da floresta", "Latina", "Nome natural"),
    ("Tereza", "Caçadora", "Grega", "Nome de santa"),
    ("Ubaldo", "Coragem", "Germânica", "Nome antigo"),
    ("Valéria", "Saúde", "Latina", "Significado positivo"),
    ("Waldir", "Governante do exército", "Germânica", "Nome forte"),
    ("Xavier", "Novo lar", "Basco", "Nome de santo"),
    ("Yasmin", "Flor de jasmim", "Persa", "Nome floral"),
    ("Zélia", "Zelosa", "Grega", "Nome diferente"),
    ("Abílio", "Pastor", "Grega", "Nome histórico"),
    ("Benedita", "Abençoada", "Latina", "Nome religioso"),
    ("Cremilda", "Protetora famosa", "Germânica", "Nome antigo"),
    ("Delfim", "Golfinho", "Grega", "Nome mitológico"),
    ("Edmundo", "Protetor da prosperidade", "Germânica", "Nome histórico"),
    ("Florinda", "Florida", "Latina", "Nome floral"),
    ("Geralda", "Lança governante", "Germânica", "Nome forte"),
    ("Hermínio", "Mensageiro", "Grega", "Nome histórico"),
    ("Ilda", "Guerreira", "Germânica", "Nome antigo"),
    ("Jacinto", "Flor", "Grega", "Nome floral"),
    ("Kléber", "Famoso", "Germânica", "Nome forte"),
    ("Ludovico", "Guerreiro famoso", "Germânica", "Nome histórico"),
    ("Marlene", "Combinação de Maria e Madalena", "Germânica", "Nome composto"),
    ("Neide", "Presente", "Grega", "Nome simples"),
    ("Odir", "Rico", "Germânica", "Nome antigo"),
    ("Plínio", "Cheio", "Latina", "Nome histórico"),
    ("Quirino", "Lança", "Latina", "Nome histórico"),
    ("Rosana", "Graciosa como uma rosa", "Latina", "Nome floral"),
    ("Simeão", "Ouvinte", "Hebraica", "Nome bíblico"),
    ("Terezinha", "Pequena caçadora", "Grega", "Diminutivo de Tereza"),
    ("Ubiratã", "Árvore forte", "Tupi", "Nome indígena"),
    ("Vanderlei", "Viajante do vale", "Germânica", "Nome composto"),
    ("Waldete", "Luta do governante", "Germânica", "Nome composto"),
    ("Xisto", "Polido", "Grega", "Nome incomum"),
    ("Yara", "Senhora das águas", "Tupi", "Nome indígena"),
    ("Zacarias", "Deus lembrou", "Hebraica", "Nome bíblico"),
    ("Abner", "Pai da luz", "Hebraica", "Nome bíblico"),
    ("Baltazar", "Deus protege o rei", "Babilônica", "Nome bíblico"),
    ("Cássia", "Canela", "Grega", "Nome aromático"),
    ("Débora", "Abelha", "Hebraica", "Nome bíblico"),
    ("Enoque", "Iniciado", "Hebraica", "Nome bíblico"),
    ("Firmino", "Firme", "Latina", "Nome forte"),
    ("Gideão", "Cortador", "Hebraica", "Nome bíblico"),
    ("Hagar", "Fuga", "Hebraica", "Nome bíblico"),
    ("Ivonete", "Arco de teixo", "Francesa", "Nome diferente"),
    ("Jeremias", "Deus exaltará", "Hebraica", "Nome bíblico"),
    ("Ketlyn", "Pura", "Irlandesa", "Variante de Caitlin"),
    ("Lázaro", "Deus ajudou", "Hebraica", "Nome bíblico"),
    ("Malaquias", "Meu mensageiro", "Hebraica", "Nome bíblico"),
    ("Noé", "Descanso", "Hebraica", "Nome bíblico"),
    ("Oseias", "Salvação", "Hebraica", "Nome bíblico"),
    ("Perséfone", "Aquela que traz destruição", "Grega", "Nome mitológico"),
    ("Queops", "Protegido", "Egípcia", "Nome histórico"),
    ("Raabe", "Amplo", "Hebraica", "Nome bíblico"),
    ("Sansão", "Pequeno sol", "Hebraica", "Nome bíblico"),
    ("Talita", "Menina", "Aramaica", "Nome bíblico"),
    ("Urias", "Deus é minha luz", "Hebraica", "Nome bíblico"),
    ("Vasti", "Bela", "Persa", "Nome bíblico"),
    ("Werther", "Guardião do exército", "Germânica", "Nome literário"),
    ("Xerxes", "Governante", "Persa", "Nome histórico"),
    ("Yasmin", "Flor de jasmim", "Persa", "Nome floral"),
    ("Zebedeu", "Presente de Deus", "Hebraica", "Nome bíblico"),
    ("Aban", "Água", "Persa", "Nome diferente"),
    ("Bastião", "Venerável", "Grega", "Variante de Sebastião"),
    ("Cibele", "Mãe terra", "Frígia", "Nome mitológico"),
    ("Dagmar", "Dia glorioso", "Escandinava", "Nome real"),
    ("Edivaldo", "Governante rico", "Germânica", "Nome composto"),
    ("Fábia", "Agricultora", "Latina", "Nome histórico"),
    ("Giane", "Deus é gracioso", "Italiana", "Variante de Giovana"),
    ("Hilel", "Louvado", "Hebraica", "Nome bíblico"),
    ("Iracema", "Lábios de mel", "Tupi", "Nome literário"),
    ("Jaci", "Lua", "Tupi", "Nome indígena"),
    ("Kailane", "Pura", "Irlandesa", "Variante de Caitlin"),
    ("Líder", "Condutor", "Inglesa", "Nome moderno"),
    ("Maíra", "Filha de Araci", "Tupi", "Nome indígena"),
    ("Nelson", "Filho de Neil", "Inglesa", "Nome moderno"),
    ("Oziel", "Força de Deus", "Hebraica", "Nome bíblico"),
    ("Pérola", "Pérola", "Latina", "Nome de gema"),
    ("Querubim", "Anjo", "Hebraica", "Nome angelical"),
    ("Rute", "Amizade", "Hebraica", "Nome bíblico"),
    ("Salomé", "Paz", "Hebraica", "Nome bíblico"),
    ("Társis", "Pedra preciosa", "Hebraica", "Nome bíblico"),
    ("Uziel", "Força de Deus", "Hebraica", "Nome bíblico"),
    ("Vânia", "Deus é gracioso", "Russa", "Variante de Ana"),
    ("Wanda", "Andarilha", "Eslava", "Nome diferente"),
    ("Xena", "Hospedeira", "Grega", "Nome de personagem"),
    ("Yara", "Senhora das águas", "Tupi", "Nome indígena"),
    ("Zara", "Princesa", "Árabe", "Nome real"),
    ("Açucena", "Flor", "Árabe", "Nome floral"),
    ("Berenice", "Portadora da vitória", "Grega", "Nome histórico"),
    ("Cássio", "Vazio", "Latina", "Nome histórico"),
    ("Dália", "Flor", "Grega", "Nome floral"),
    ("Edna", "Prazer", "Hebraica", "Nome bíblico"),
    ("Floriano", "Florido", "Latina", "Nome floral"),
    ("Glaucia", "Brilho cinza", "Grega", "Nome mitológico"),
    ("Hélia", "Sol", "Grega", "Nome mitológico"),
    ("Ivanir", "Deus é gracioso", "Russa", "Variante de João"),
    ("Jandira", "Abelha", "Tupi", "Nome indígena"),
    ("Kauê", "Aquele que vê", "Tupi", "Nome indígena"),
    ("Lavínia", "Mulher de Lácio", "Latina", "Nome histórico"),
    ("Márcia", "Guerreira", "Latina", "Nome forte"),
    ("Nair", "Negra", "Árabe", "Nome simples"),
    ("Olavo", "Herdeiro", "Escandinava", "Nome real"),
    ("Priscila", "Antiga", "Latina", "Nome bíblico"),
    ("Querência", "Lar", "Espanhola", "Nome poético"),
    ("Rogério", "Lança famosa", "Germânica", "Nome forte"),
    ("Sílvio", "Da floresta", "Latina", "Nome natural"),
    ("Tereza", "Caçadora", "Grega", "Nome de santa"),
    ("Ubaldo", "Coragem", "Germânica", "Nome antigo"),
    ("Valéria", "Saúde", "Latina", "Significado positivo"),
    ("Waldir", "Governante do exército", "Germânica", "Nome forte"),
    ("Xavier", "Novo lar", "Basco", "Nome de santo"),
    ("Yasmin", "Flor de jasmim", "Persa", "Nome floral"),
    ("Zélia", "Zelosa", "Grega", "Nome diferente"),
    ("Abílio", "Pastor", "Grega", "Nome histórico"),
    ("Benedita", "Abençoada", "Latina", "Nome religioso"),
    ("Cremilda", "Protetora famosa", "Germânica", "Nome antigo"),
    ("Delfim", "Golfinho", "Grega", "Nome mitológico"),
    ("Edmundo", "Protetor da prosperidade", "Germânica", "Nome histórico"),
    ("Florinda", "Florida", "Latina", "Nome floral"),
    ("Geralda", "Lança governante", "Germânica", "Nome forte"),
    ("Hermínio", "Mensageiro", "Grega", "Nome histórico"),
    ("Ilda", "Guerreira", "Germânica", "Nome antigo"),
    ("Jacinto", "Flor", "Grega", "Nome floral"),
    ("Kléber", "Famoso", "Germânica", "Nome forte"),
    ("Ludovico", "Guerreiro famoso", "Germânica", "Nome histórico"),
    ("Marlene", "Combinação de Maria e Madalena", "Germânica", "Nome composto"),
    ("Neide", "Presente", "Grega", "Nome simples"),
    ("Odir", "Rico", "Germânica", "Nome antigo"),
    ("Plínio", "Cheio", "Latina", "Nome histórico"),
    ("Quirino", "Lança", "Latina", "Nome histórico"),
    ("Rosana", "Graciosa como uma rosa", "Latina", "Nome floral"),
    ("Simeão", "Ouvinte", "Hebraica", "Nome bíblico"),
    ("Terezinha", "Pequena caçadora", "Grega", "Diminutivo de Tereza"),
    ("Ubiratã", "Árvore forte", "Tupi", "Nome indígena"),
    ("Vanderlei", "Viajante do vale", "Germânica", "Nome composto"),
    ("Waldete", "Luta do governante", "Germânica", "Nome composto"),
    ("Xisto", "Polido", "Grega", "Nome incomum"),
    ("Yara", "Senhora das águas", "Tupi", "Nome indígena"),
    ("Zacarias", "Deus lembrou", "Hebraica", "Nome bíblico"),
    ("Abner", "Pai da luz", "Hebraica", "Nome bíblico"),
    ("Baltazar", "Deus protege o rei", "Babilônica", "Nome bíblico"),
    ("Cássia", "Canela", "Grega", "Nome aromático"),
    ("Débora", "Abelha", "Hebraica", "Nome bíblico"),
    ("Enoque", "Iniciado", "Hebraica", "Nome bíblico"),
    ("Firmino", "Firme", "Latina", "Nome forte"),
    ("Gideão", "Cortador", "Hebraica", "Nome bíblico"),
    ("Hagar", "Fuga", "Hebraica", "Nome bíblico"),
    ("Ivonete", "Arco de teixo", "Francesa", "Nome diferente"),
    ("Jeremias", "Deus exaltará", "Hebraica", "Nome bíblico"),
    ("Ketlyn", "Pura", "Irlandesa", "Variante de Caitlin"),
    ("Lázaro", "Deus ajudou", "Hebraica", "Nome bíblico"),
    ("Malaquias", "Meu mensageiro", "Hebraica", "Nome bíblico"),
    ("Noé", "Descanso", "Hebraica", "Nome bíblico"),
    ("Oseias", "Salvação", "Hebraica", "Nome bíblico"),
    ("Perséfone", "Aquela que traz destruição", "Grega", "Nome mitológico"),
    ("Queops", "Protegido", "Egípcia", "Nome histórico"),
    ("Raabe", "Amplo", "Hebraica", "Nome bíblico"),
    ("Sansão", "Pequeno sol", "Hebraica", "Nome bíblico"),
    ("Talita", "Menina", "Aramaica", "Nome bíblico"),
    ("Urias", "Deus é minha luz", "Hebraica", "Nome bíblico"),
    ("Vasti", "Bela", "Persa", "Nome bíblico"),
    ("Werther", "Guardião do exército", "Germânica", "Nome literário"),
    ("Xerxes", "Governante", "Persa", "Nome histórico"),
    ("Yasmin", "Flor de jasmim", "Persa", "Nome floral"),
    ("Zebedeu", "Presente de Deus", "Hebraica", "Nome bíblico"),
    ("Aban", "Água", "Persa", "Nome diferente"),
    ("Bastião", "Venerável", "Grega", "Variante de Sebastião"),
    ("Cibele", "Mãe terra", "Frígia", "Nome mitológico"),
    ("Dagmar", "Dia glorioso", "Escandinava", "Nome real"),
    ("Edivaldo", "Governante rico", "Germânica", "Nome composto"),
    ("Fábia", "Agricultora", "Latina", "Nome histórico"),
    ("Giane", "Deus é gracioso", "Italiana", "Variante de Giovana"),
    ("Hilel", "Louvado", "Hebraica", "Nome bíblico"),
    ("Iracema", "Lábios de mel", "Tupi", "Nome literário"),
    ("Jaci", "Lua", "Tupi", "Nome indígena"),
    ("Kailane", "Pura", "Irlandesa", "Variante de Caitlin"),
    ("Líder", "Condutor", "Inglesa", "Nome moderno"),
    ("Maíra", "Filha de Araci", "Tupi", "Nome indígena"),
    ("Nelson", "Filho de Neil", "Inglesa", "Nome moderno"),
    ("Oziel", "Força de Deus", "Hebraica", "Nome bíblico"),
    ("Pérola", "Pérola", "Latina", "Nome de gema"),
    ("Querubim", "Anjo", "Hebraica", "Nome angelical"),
    ("Rute", "Amizade", "Hebraica", "Nome bíblico"),
    ("Salomé", "Paz", "Hebraica", "Nome bíblico"),
    ("Társis", "Pedra preciosa", "Hebraica", "Nome bíblico"),
    ("Uziel", "Força de Deus", "Hebraica", "Nome bíblico"),
    ("Vânia", "Deus é gracioso", "Russa", "Variante de Ana"),
    ("Wanda", "Andarilha", "Eslava", "Nome diferente"),
    ("Xena", "Hospedeira", "Grega", "Nome de personagem"),
    ("Yara", "Senhora das águas", "Tupi", "Nome indígena"),
    ("Zara", "Princesa", "Árabe", "Nome real"),
    ("Açucena", "Flor", "Árabe", "Nome floral"),
    ("Berenice", "Portadora da vitória", "Grega", "Nome histórico"),
    ("Cássio", "Vazio", "Latina", "Nome histórico"),
    ("Dália", "Flor", "Grega", "Nome floral"),
    ("Edna", "Prazer", "Hebraica", "Nome bíblico"),
    ("Floriano", "Florido", "Latina", "Nome floral"),
    ("Glaucia", "Brilho cinza", "Grega", "Nome mitológico"),
    ("Hélia", "Sol", "Grega", "Nome mitológico"),
    ("Ivanir", "Deus é gracioso", "Russa", "Variante de João"),
    ("Jandira", "Abelha", "Tupi", "Nome indígena"),
    ("Kauê", "Aquele que vê", "Tupi", "Nome indígena"),
    ("Lavínia", "Mulher de Lácio", "Latina", "Nome histórico"),
    ("Márcia", "Guerreira", "Latina", "Nome forte"),
    ("Nair", "Negra", "Árabe", "Nome simples"),
    ("Olavo", "Herdeiro", "Escandinava", "Nome real"),
    ("Priscila", "Antiga", "Latina", "Nome bíblico"),
    ("Querência", "Lar", "Espanhola", "Nome poético"),
    ("Rogério", "Lança famosa", "Germânica", "Nome forte"),
    ("Sílvio", "Da floresta", "Latina", "Nome natural"),
    ("Tereza", "Caçadora", "Grega", "Nome de santa"),
    ("Ubaldo", "Coragem", "Germânica", "Nome antigo"),
    ("Valéria", "Saúde", "Latina", "Significado positivo"),
    ("Waldir", "Governante do exército", "Germânica", "Nome forte"),
    ("Xavier", "Novo lar", "Basco", "Nome de santo"),
    ("Yasmin", "Flor de jasmim", "Persa", "Nome floral"),
    ("Zélia", "Zelosa", "Grega", "Nome diferente"),
    ("Abílio", "Pastor", "Grega", "Nome histórico"),
    ("Benedita", "Abençoada", "Latina", "Nome religioso"),
    ("Cremilda", "Protetora famosa", "Germânica", "Nome antigo"),
    ("Delfim", "Golfinho", "Grega", "Nome mitológico"),
    ("Edmundo", "Protetor da prosperidade", "Germânica", "Nome histórico"),
    ("Florinda", "Florida", "Latina", "Nome floral"),
    ("Geralda", "Lança governante", "Germânica", "Nome forte"),
    ("Hermínio", "Mensageiro", "Grega", "Nome histórico"),
    ("Ilda", "Guerreira", "Germânica", "Nome antigo"),
    ("Jacinto", "Flor", "Grega", "Nome floral"),
    ("Kléber", "Famoso", "Germânica", "Nome forte"),
    ("Ludovico", "Guerreiro famoso", "Germânica", "Nome histórico"),
    ("Marlene", "Combinação de Maria e Madalena", "Germânica", "Nome composto"),
    ("Neide", "Presente", "Grega", "Nome simples"),
    ("Odir", "Rico", "Germânica", "Nome antigo"),
    ("Plínio", "Cheio", "Latina", "Nome histórico"),
    ("Quirino", "Lança", "Latina", "Nome histórico"),
    ("Rosana", "Graciosa como uma rosa", "Latina", "Nome floral"),
    ("Simeão", "Ouvinte", "Hebraica", "Nome bíblico"),
    ("Terezinha", "Pequena caçadora", "Grega", "Diminutivo de Tereza"),
    ("Ubiratã", "Árvore forte", "Tupi", "Nome indígena"),
    ("Vanderlei", "Viajante do vale", "Germânica", "Nome composto"),
    ("Waldete", "Luta do governante", "Germânica", "Nome composto"),
    ("Xisto", "Polido", "Grega", "Nome incomum"),
    ("Yara", "Senhora das águas", "Tupi", "Nome indígena"),
    ("Zacarias", "Deus lembrou", "Hebraica", "Nome bíblico"),
    ("Abner", "Pai da luz", "Hebraica", "Nome bíblico"),
    ("Baltazar", "Deus protege o rei", "Babilônica", "Nome bíblico"),
    ("Cássia", "Canela", "Grega", "Nome aromático"),
    ("Débora", "Abelha", "Hebraica", "Nome bíblico"),
    ("Enoque", "Iniciado", "Hebraica", "Nome bíblico"),
    ("Firmino", "Firme", "Latina", "Nome forte"),
    ("Gideão", "Cortador", "Hebraica", "Nome bíblico"),
    ("Hagar", "Fuga", "Hebraica", "Nome bíblico"),
    ("Ivonete", "Arco de teixo", "Francesa", "Nome diferente"),
    ("Jeremias", "Deus exaltará", "Hebraica", "Nome bíblico"),
    ("Ketlyn", "Pura", "Irlandesa", "Variante de Caitlin"),
    ("Lázaro", "Deus ajudou", "Hebraica", "Nome bíblico"),
    ("Malaquias", "Meu mensageiro", "Hebraica", "Nome bíblico"),
    ("Noé", "Descanso", "Hebraica", "Nome bíblico"),
    ("Oseias", "Salvação", "Hebraica", "Nome bíblico"),
    ("Perséfone", "Aquela que traz destruição", "Grega", "Nome mitológico"),
    ("Queops", "Protegido", "Egípcia", "Nome histórico"),
    ("Raabe", "Amplo", "Hebraica", "Nome bíblico"),
    ("Sansão", "Pequeno sol", "Hebraica", "Nome bíblico"),
    ("Talita", "Menina", "Aramaica", "Nome bíblico"),
    ("Urias", "Deus é minha luz", "Hebraica", "Nome bíblico"),
    ("Vasti", "Bela", "Persa", "Nome bíblico"),
    ("Werther", "Guardião do exército", "Germânica", "Nome literário"),
    ("Xerxes", "Governante", "Persa", "Nome histórico"),
    ("Yasmin", "Flor de jasmim", "Persa", "Nome floral"),
    ("Zebedeu", "Presente de Deus", "Hebraica", "Nome bíblico"),
    ("Aban", "Água", "Persa", "Nome diferente"),
    ("Bastião", "Venerável", "Grega", "Variante de Sebastião"),
    ("Cibele", "Mãe terra", "Frígia", "Nome mitológico"),
    ("Dagmar", "Dia glorioso", "Escandinava", "Nome real"),
    ("Edivaldo", "Governante rico", "Germânica", "Nome composto"),
    ("Fábia", "Agricultora", "Latina", "Nome histórico"),
    ("Giane", "Deus é gracioso", "Italiana", "Variante de Giovana"),
    ("Hilel", "Louvado", "Hebraica", "Nome bíblico"),
    ("Iracema", "Lábios de mel", "Tupi", "Nome literário"),
    ("Jaci", "Lua", "Tupi", "Nome indígena"),
    ("Kailane", "Pura", "Irlandesa", "Variante de Caitlin"),
    ("Líder", "Condutor", "Inglesa", "Nome moderno"),
    ("Maíra", "Filha de Araci", "Tupi", "Nome indígena"),
    ("Nelson", "Filho de Neil", "Inglesa", "Nome moderno"),
    ("Oziel", "Força de Deus", "Hebraica", "Nome bíblico"),
    ("Pérola", "Pérola", "Latina", "Nome de gema"),
    ("Querubim", "Anjo", "Hebraica", "Nome angelical"),
    ("Rute", "Amizade", "Hebraica", "Nome bíblico"),
    ("Salomé", "Paz", "Hebraica", "Nome bíblico"),
    ("Társis", "Pedra preciosa", "Hebraica", "Nome bíblico"),
    ("Uziel", "Força de Deus", "Hebraica", "Nome bíblico"),
    ("Vânia", "Deus é gracioso", "Russa", "Variante de Ana"),
    ("Wanda", "Andarilha", "Eslava", "Nome diferente"),
    ("Xena", "Hospedeira", "Grega", "Nome de personagem"),
    ("Yara", "Senhora das águas", "Tupi", "Nome indígena"),
    ("Zara", "Princesa", "Árabe", "Nome real"),
    ("Açucena", "Flor", "Árabe", "Nome floral"),
    ("Berenice", "Portadora da vitória", "Grega", "Nome histórico"),
    ("Cássio", "Vazio", "Latina", "Nome histórico"),
    ("Dália", "Flor", "Grega", "Nome floral"),
    ("Edna", "Prazer", "Hebraica", "Nome bíblico"),
    ("Floriano", "Florido", "Latina", "Nome floral"),
    ("Glaucia", "Brilho cinza", "Grega", "Nome mitológico"),
    ("Hélia", "Sol", "Grega", "Nome mitológico"),
    ("Ivanir", "Deus é gracioso", "Russa", "Variante de João"),
    ("Jandira", "Abelha", "Tupi", "Nome indígena"),
    ("Kauê", "Aquele que vê", "Tupi", "Nome indígena"),
    ("Lavínia", "Mulher de Lácio", "Latina", "Nome histórico"),
    ("Márcia", "Guerreira", "Latina", "Nome forte"),
    ("Nair", "Negra", "Árabe", "Nome simples"),
    ("Olavo", "Herdeiro", "Escandinava", "Nome real"),
    ("Priscila", "Antiga", "Latina", "Nome bíblico"),
    ("Querência", "Lar", "Espanhola", "Nome poético"),
    ("Rogério", "Lança famosa", "Germânica", "Nome forte"),
    ("Sílvio", "Da floresta", "Latina", "Nome natural"),
    ("Tereza", "Caçadora", "Grega", "Nome de santa"),
    ("Ubaldo", "Coragem", "Germânica", "Nome antigo"),
    ("Valéria", "Saúde", "Latina", "Significado positivo"),
    ("Waldir", "Governante do exército", "Germânica", "Nome forte"),
    ("Xavier", "Novo lar", "Basco", "Nome de santo"),
    ("Yasmin", "Flor de jasmim", "Persa", "Nome floral"),
    ("Zélia", "Zelosa", "Grega", "Nome diferente")
]

duplicados = encontrar_duplicados(nomes)

print("Nomes duplicados encontrados:")
for nome, detalhes in duplicados.items():
    print(f"\n{nome} aparece {len(detalhes)} vezes:")
    for i, (significado, origem, motivacao) in enumerate(detalhes, 1):
        print(f"  {i}. Significado: {significado}, Origem: {origem}, Motivação: {motivacao}")